paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products from the DB
      responses:
        "200":
          description: Products fetched from the DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductsResponse"
        "500":
          description: Internal server error
    post:
      tags:
        - Products
      summary: Create a product into DB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/CreateProductPayload"
      responses:
        "200":
          description: Product created to the DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Invalid body format.
        "500":
          description: Internal server error

  /api/products/{productId}:
    get:
      tags:
        - Products
      summary: Get a single product by their id
      parameters:
        - name: productId
          in: path
          required: true
          description: ProducId to fetch
          schema:
            $type: string
      responses:
        "200":
          description: Product by id fetched from the DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "500":
          description: Internal server error
    put:
      tags:
        - Products
      summary: Updates a single product by an id
      parameters:
        - name: productId
          in: path
          required: true
          description: ProducId to update
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/UpdateProductPayload"
      responses:
        "200":
          description: Product by id updated from the DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Invalid body format.
        "404":
          description: User ID not found
        "500":
          description: Internal server error
    delete:
      tags:
        - Products
      summary: Delete a single product by an id
      parameters:
        - name: productId
          in: path
          required: true
          description: ProducId to delete
          schema:
            $type: string
      responses:
        "200":
          description: Product by id deleted from the DB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "404":
          description: User ID not found
        "500":
          description: Internal server error




components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Autogenerated MongoDB ID
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        code:
          type: string
          description: Product code (Unique field)
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        category:
          type: string
          description: Product category
        status:
          type: boolean
          description: Autogenerated MongoDB ID
        thumbnails:
          type: array
          description: Autogenerated MongoDB ID
      example:
        _id: ObjectId(123abc456def) # <== Ver que onda
        title: Remera Levis
        description: Remera Levis manga corta
        code: 123456
        price: 1000
        stock: 10
        category: Remeras
        status: true
        thumbnails:
          [
            https://www.google.com.ar/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png,
          ]

    ProductsResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Products response status
          enum: [true, false]
        data:
          type: array
          description: Products array list
          items:
            $ref: "#/components/schemas/Product"

    ProductResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Products response status
          enum: [true, false]
        data:
          $ref: "#/components/schemas/Product"

  requestBodies:
    CreateProductPayload:
      type: object
      properties:
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        code:
          type: string
          description: Product code (Unique field)
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        category:
          type: string
          description: Product category
        status:
          type: boolean
          description: Autogenerated MongoDB ID
        thumbnails:
          type: array
          description: Autogenerated MongoDB ID
      example:
        _id: ObjectId(123abc456def)
        title: Remera Levis
        description: Remera Levis manga corta
        code: 123456
        price: 1000
        stock: 10
        category: Remeras
        status: true
        thumbnails:
          [
            https://www.google.com.ar/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png,
          ]
    UpdateProductPayload:
      type: object
      properties:
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        code:
          type: string
          description: Product code (Unique field)
        price:
          type: number
          description: Product price
        stock:
          type: number
          description: Product stock
        category:
          type: string
          description: Product category
        status:
          type: boolean
          description: Autogenerated MongoDB ID
        thumbnails:
          type: array
          description: Autogenerated MongoDB ID
      example:
        _id: ObjectId(123abc456def)
        title: Remera Levis
        description: Remera Levis manga corta
        code: 123456
        price: 1000
        stock: 10
        category: Remeras
        status: true
        thumbnails:
          [
            https://www.google.com.ar/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png,
          ]
